all: dfs uva-469 kruskal_prim bfs dijkstra bellman_ford floyd_warshall edmonds_karp mcbm

dfs: ch4_01_dfs.cpp
	g++ -std=c++11 -o dfs ch4_01_dfs.cpp

uva-469: ch4_02_UVa469.cpp
	g++ -std=c++11 -o uva-469 ch4_02_UVa469.cpp
#ch4_03_kruskal_prim.cpp
#ch4_04_bfs.cpp
#ch4_05_dijkstra.cpp
#ch4_06_bellman_ford.cpp
#ch4_07_floyd_warshall.cpp
#ch4_08_edmonds_karp.cpp
#ch4_09_mcbm.cpp

